### ISSUE TITLE
Unable to import into vue project

### ISSUE THREAD

**Issue by abhaybhargav** [DominikAngerer/vue-heatmap#1]
I am unable to import this into my vue project. 

I have done: `npm install -- save vuejs-heatmap`

I am trying to use this `import calendarHeatmap from 'vuejs-heatmap'`

I am getting the error: `Module not found: Error: Can't resolve 'vuejs-heatmap' in /path/`

Not sure what I am doing wrong

**Comment by DominikAngerer** [comment]
Hey there,
Sorry to hear that - I've restructured the app and republished it so you can use it directly. The main idea was to showcase the possibility to add the heatmap to your projects so you can customize it.

You're now able to use:

```
npm install --save vuejs-heatmap
# or
yarn add vuejs-heatmap
```

to install your dependency, and you're able to import and use it like shown below:

```
<VuejsHeatmap/>

<script>
import VuejsHeatmap from 'vuejs-heatmap'

export default {
  name: 'App',
  components: {
    VuejsHeatmap
  }
}
</script>
```
