### ISSUE TITLE
Cannot use multiple times in same .vue file

### ISSUE THREAD

**Issue by dakshshah96** [DominikAngerer/vue-heatmap#4]
First of all, thanks for making this super useful project 😄 

**Problem**

I have a parent page (`UserPage.vue`) which imports various components from other files (`TripsTab.vue`, `BookingsTab.vue`) and each one of these uses `<VuejsHeatmap> </VuejsHeatmap>` so in the resulting page there will be multiple instances of `<VuejsHeatmap> </VuejsHeatmap>`.

Only the first instance of `<VuejsHeatmap> </VuejsHeatmap>` is rendered. None of the others are rendered.

What could be the cause for this?

**Comment by DominikAngerer** [comment]
Hey there! Most of the work was done by @DKirwan! I've wrapped it into a vue component.

I'll have a look into it and publish a new version as soon as it's done.

**Comment by dakshshah96** [comment]
@DominikAngerer I understand. Thanks a lot!

Please let me know if you can figure out what the problem might be. I can roll out my Vue app ASAP then 😉

**Comment by DKirwan** [comment]
Thanks guys! It looks like the `selector` just needs to be unique for each one

**Comment by dakshshah96** [comment]
@DKirwan Thanks for the clarification!

@DominikAngerer How do I do this with vue-heatmap? I have no clue. Thanks again for bearing with me 😅

**Comment by DominikAngerer** [comment]
Version 1.1.6 is out now - sorry for the week waiting. Thanks @DKirwan - thats correct.

@dakshshah96 You can add `:selector="'myFirstCustomSelector'"` or `selector="myFirstCustomSelector"` as property resulting in a custom selector and therefore multiple instances of the heatmap. I've also fixed a bug where the default rendering would be added to `body`.

Example with 3 Heatmaps and 3 different color schemes:

![Example of multiple heatmaps](https://user-images.githubusercontent.com/7952803/40014813-d3ee9b7c-57b1-11e8-86b0-5f985d9d1346.jpg)

Commit: 4af02facd0e1643042607daaf228d1e1b7e30adf

**Comment by dakshshah96** [comment]
@DominikAngerer That was quick, no problem at all! Thanks for the help. 😄
